---
- name: Converge
  hosts: all
  tasks:
    - name: "Include wandansible.chrony"
      ansible.builtin.include_role:
        name: "wandansible.chrony"
      vars:
        chrony_modern: >-
          {{ true if
          (ansible_distribution == "Ubuntu" and ansible_distribution_version is version('20.04', '>=')) or
          (ansible_distribution == "Debian" and ansible_distribution_version is version('11', '>='))
          else false }}

        chrony_config: |
          {% if chrony_modern %}
          # Include configuration files found in /etc/chrony/conf.d.
          confdir /etc/chrony/conf.d

          # Use time sources from DHCP.
          sourcedir /run/chrony-dhcp

          # Use NTP sources found in /etc/chrony/sources.d.
          sourcedir /etc/chrony/sources.d

          # Save NTS keys and cookies.
          ntsdumpdir /var/lib/chrony
          {% endif %}

          # This directive specify the location of the file containing ID/key pairs for
          # NTP authentication.
          keyfile /etc/chrony/chrony.keys

          # This directive specify the file into which chronyd will store the rate
          # information.
          driftfile /var/lib/chrony/chrony.drift

          # Log files location.
          logdir /var/log/chrony

          # Stop bad estimates upsetting machine clock.
          maxupdateskew 100.0

          # Step the system clock instead of slewing it if the adjustment is larger than
          # one second, but only in the first three clock updates.
          makestep 1 3

        chrony_config_d:
          - name: leap-smear
            config: |
              # Slew leap seconds across a day
              leapsecmode slew
              maxslewrate 1000

        chrony_sources:
          - "pool ntp.ubuntu.com iburst maxsources 4"
          - "pool 0.ubuntu.pool.ntp.org iburst maxsources 1"
          - "pool 1.ubuntu.pool.ntp.org iburst maxsources 1"
          - "pool 2.ubuntu.pool.ntp.org iburst maxsources 2"
